### ISSUE TITLE
alfresco user shoud be able to login ? (.bash_profile)

### ISSUE THREAD

**Issue by Giuliano69** [jpotts/ansible-alfresco#1]
Hi jpotts,
the task doCopyAlfrescoConfig.yml is copying the alfresco bash profile in the managed server.

Usually the alfresco user is supposed to be created as a system user, that is a not loging user like
sudo adduser --system --disabled-login --disabled-password --group "$ALF_USER"

Considering you are copying the interactive bash profile, with your installation do you intend the alfresco user to be able to log in ?
When do you need to log in as alfresco user ?

**Comment by jpotts** [comment]
You are correct, there is no strict requirement for the alfresco user to be able to log in. It can be handy to have JAVA_HOME set properly when switching to this user. Probably it would be better just to remove the bash profile from this code base and not copy it at all to reduce confusion.

**Comment by jpotts** [comment]
Thanks for the issue @Giuliano69

**Comment by Giuliano69** [comment]
Hi jpots,
I made some tests using the alfresco user, created as NOT capable of logging
`--system --disabled-login --disabled-password `
What I discovered was that ansible is using a ssh tunnel ....  BUT  to make ssh work we need a user capable of logging !!
I'm new to ansible, but for what I 've seen  Ansible need the user to be capable of logging (and have a usual home dir). 
So alfresco user must be created as  a "normal" one.

Even more, I would NOT transfer the bash profile..
In the fork I made from your project, you can see I've prepared two bash script that prepare the control node and the managed node for the ansible scripts. 
In particular the managed node bash script, together with other installations, is installing Java and saving the JAVA_HOME variable path at system level.

It maybe perfect if all this changes (installations) provided by the two bash scripts, in the managed and control node, would be provided by some other Ansible scripts.
