### ISSUE TITLE
Vault password file .vault-passwd missing ?

### ISSUE THREAD

**Issue by Giuliano69** [jpotts/ansible-alfresco#2]
Hi jpotts,
in ansible.cfg,  the following file is pointed
vault_password_file = .vault-passwd
but it is NOT PRESENT in the directory.
I get this error: Using ansible 2.9.6 
```
$ ansible-playbook installAlfresco.yml --extra-vars="hosts=alfresco_test"
ERROR! The vault password file /home/giuliano/Scrivania/alfresco/ansible-alfresco-master/.vault-passwd was not found
```
Is the password file .vault-password missing ?
Which is the password ?

ALSO
I see in vars that exist some passowrd crypted in vault (alfrescodb, alfresco admin,....) But I cannot find how to decript them:
 ,  When I try
`$ ansible-vault edit group_vars/all/vault `
I get (I tried the passords: admin, alfresco, ...) :
```
Vault password: 
ERROR! Decryption failed (no vault secrets were found that could decrypt) for /home/giuliano/Scrivania/alfresco/ansible-alfresco-master/group_vars/all/vault
```
PS
Googling around I found that there are some problems with .vault-passowrd. 
But I should be using a version NOT affected by such bug.
https://github.com/ansible/ansible/issues/32486

**Comment by jpotts** [comment]
I can update the README.md to make this more clear. You will need to re-create and re-encrypt your own vault files. This also requires you to establish your own vault password.

I suppose I could use a simple and well-known password and distribute that along with instructions on how to change the password and how to re-encrypt. But it is probably better to:

1. continue to not distribute a password file 
2. delete the vault files from source code control
3. update the docs with information on what should go in the vault files and how to encrypt them the first time after setting a vault password

**Comment by jpotts** [comment]
Thanks for the issue @Giuliano69

**Comment by Giuliano69** [comment]
I would better suggest to have the project WITHOUT any cripted password . If anyone would like to improve security, he will find a way to manage it at his will (implementing the preferred solutions) 
Keeping it silly simple, we can assure that everything works out of the box (KISS)

I positively succeeded in installing Aflresco on the Raspi4-8Gb (it works!) , 
BUT I had to edit  the all/vars file, and CHANGE the {{ vault labels with a plain text "password".
Unfortunately it DID NOT work completely. !! I could NOT login as admin, even if I set
alf_initial_admin_password: "admin"
in my var file...

this is VERY strange and make me believe that would be more useful and installation with NO vault, to better understand WHERE could some problems exist. And be corrected quikly
In my case , I had to follow 
https://docs.alfresco.com/5.0/concepts/admin-password.html
enter with pgadmin4 the database, and reset the password. 
I noticed that the password for the admin user returned from the SELECT was EMPTY, meaning that a simple vault password substitution didn't work... maybe it was NOT set for some config reasons ?
After I inserted by hand the hashed password, the new SELECT showed the expected result.

Maybe there are some other things to change or to remove in the vault file, but starting from a configuration that has NO vault, would prevent any modification to miss some critical point....

BR
Giuliano

**Comment by jpotts** [comment]
The initial admin password is not what you think it is. That must be an encrypted value. md5, I believe. The value that I ship with is the encrypted value for "admin" which is what the old installer used as the default password. Shipping with an unencrypted vault would not have solved this problem because that particular property would still be encrypted.

The project currently works out-of-the-box when setting the vault with the values as instructed and then logging in as admin/admin.

**Comment by Giuliano69** [comment]
thanks Jpotts. 
The chiper used is md4 (historical reasons?) . We could use any password we want, just calculating the hash to be used. 
For example, the hash for admin is :
printf '%s' admin | iconv -t utf16le | openssl md4

If of interest, we could make a notice about it in the script instructions....

**Comment by jpotts** [comment]
My goal with this example project was to approximate what the old installer used to do. Because the old installer always used admin/admin, I'm inclined to keep the scripts that way. Of course people can figure out how to set that initial admin password and change the script as they see fit. They can also just let it install and then change the admin password via the UI.

**Comment by CesarCapillas** [comment]
Hi:

Just one note, MD4 passwords were used in the past for compatibility with CIFS authentication subsystem in Alfresco.

Regards.
--C.
